export enum Fonts {
  INTER100 = 'Inter-Thin',
  INTER200 = 'Inter-ExtraLight',
  INTER300 = 'Inter-Light',
  INTER400 = 'Inter-Regular',
  INTER500 = 'Inter-Medium',
  INTER600 = 'Inter-SemiBold',
  INTER700 = 'Inter-Bold',
  INTER800 = 'Inter-ExtraBold',
  INTER900 = 'Inter-Black',
  ROBOTO100 = 'Roboto-Thin',
  ROBOTO100italic = 'Roboto-ThinItalic',
  ROBOTO300 = 'Roboto-Light',
  ROBOTO300italic = 'Roboto-LightItalic',
  ROBOTO400 = 'Roboto-Regular',
  ROBOTO500 = 'Roboto-Medium',
  ROBOTO500italic = 'Roboto-MediumItalic',
  ROBOTO700 = 'Roboto-Bold',
  ROBOTO700italic = 'Roboto-BoldItalic',
  ROBOTO900 = 'Roboto-Black',
  ROBOTO900italic = 'Roboto-BlackItalic',
}
